import { Platform } from 'react-native';

// Responsive constants for consistent sizing across the app
export const RESPONSIVE_CONSTANTS = {
  // Header and navigation
  HEADER_HEIGHT: 60,
  TAB_BAR_HEIGHT: 60,
  
  // Button sizes
  BUTTON_HEIGHT_SM: 36,
  BUTTON_HEIGHT_MD: 44,
  BUTTON_HEIGHT_LG: 52,
  
  // Input sizes
  INPUT_HEIGHT_SM: 36,
  INPUT_HEIGHT_MD: 44,
  INPUT_HEIGHT_LG: 52,
  
  // Card sizes
  CARD_RADIUS_SM: 8,
  CARD_RADIUS_MD: 12,
  CARD_RADIUS_LG: 16,
  
  // Icon sizes
  ICON_SIZE_SM: 16,
  ICON_SIZE_MD: 20,
  ICON_SIZE_LG: 24,
  ICON_SIZE_XL: 32,
  ICON_SIZE_XXL: 48,
  
  // Spacing
  SPACING_XS: 4,
  SPACING_SM: 8,
  SPACING_MD: 16,
  SPACING_LG: 24,
  SPACING_XL: 32,
  SPACING_XXL: 48,
  
  // Font sizes
  FONT_SIZE_XS: 12,
  FONT_SIZE_SM: 14,
  FONT_SIZE_MD: 16,
  FONT_SIZE_LG: 18,
  FONT_SIZE_XL: 20,
  FONT_SIZE_XXL: 24,
  FONT_SIZE_XXXL: 28,
  FONT_SIZE_TITLE: 32,
  
  // Border radius
  BORDER_RADIUS_SM: 4,
  BORDER_RADIUS_MD: 8,
  BORDER_RADIUS_LG: 12,
  BORDER_RADIUS_XL: 16,
  BORDER_RADIUS_XXL: 24,
  
  // Shadow radius
  SHADOW_RADIUS_SM: 2,
  SHADOW_RADIUS_MD: 4,
  SHADOW_RADIUS_LG: 8,
  
  // Elevation (Android)
  ELEVATION_SM: 2,
  ELEVATION_MD: 4,
  ELEVATION_LG: 8,
  
  // Animation durations
  ANIMATION_DURATION_FAST: 200,
  ANIMATION_DURATION_NORMAL: 300,
  ANIMATION_DURATION_SLOW: 500,
  
  // Opacity values
  OPACITY_DISABLED: 0.6,
  OPACITY_PRESSED: 0.7,
  OPACITY_OVERLAY: 0.5,
  
  // Border widths
  BORDER_WIDTH_THIN: 0.5,
  BORDER_WIDTH_NORMAL: 1,
  BORDER_WIDTH_THICK: 2,
  
  // Grid system
  GRID_COLUMNS_1: 1,
  GRID_COLUMNS_2: 2,
  GRID_COLUMNS_3: 3,
  GRID_COLUMNS_4: 4,
  
  GRID_GAP_XS: 4,
  GRID_GAP_SM: 8,
  GRID_GAP_MD: 16,
  GRID_GAP_LG: 24,
  
  // Aspect ratios
  ASPECT_RATIO_SQUARE: 1,
  ASPECT_RATIO_PORTRAIT: 3 / 4,
  ASPECT_RATIO_LANDSCAPE: 4 / 3,
  ASPECT_RATIO_WIDE: 16 / 9,
  ASPECT_RATIO_ULTRA_WIDE: 21 / 9,
  
  // Touch targets (minimum 44px for accessibility)
  TOUCH_TARGET_MIN: 44,
  TOUCH_TARGET_MD: 48,
  TOUCH_TARGET_LG: 56,
  
  // Loading indicators
  LOADING_INDICATOR_SIZE_SM: 20,
  LOADING_INDICATOR_SIZE_MD: 24,
  LOADING_INDICATOR_SIZE_LG: 32,
  
  // Progress bars
  PROGRESS_BAR_HEIGHT_SM: 4,
  PROGRESS_BAR_HEIGHT_MD: 6,
  PROGRESS_BAR_HEIGHT_LG: 8,
  
  // Badge sizes
  BADGE_SIZE_SM: 16,
  BADGE_SIZE_MD: 20,
  BADGE_SIZE_LG: 24,
  
  // Chip sizes
  CHIP_HEIGHT_SM: 28,
  CHIP_HEIGHT_MD: 32,
  CHIP_HEIGHT_LG: 36,
  
  // FAB (Floating Action Button) sizes
  FAB_SIZE_SM: 40,
  FAB_SIZE_MD: 56,
  FAB_SIZE_LG: 64,
  
  // Tab bar
  TAB_HEIGHT: 60,
  TAB_ICON_SIZE: 24,
  
  // Switch
  SWITCH_WIDTH: 50,
  SWITCH_HEIGHT: 30,
  
  // Checkbox and Radio
  CHECKBOX_SIZE_SM: 20,
  CHECKBOX_SIZE_MD: 24,
  CHECKBOX_SIZE_LG: 28,
  
  RADIO_SIZE_SM: 20,
  RADIO_SIZE_MD: 24,
  RADIO_SIZE_LG: 28,
  
  // Modal
  MODAL_MAX_WIDTH: 400,
  MODAL_MAX_HEIGHT: 600,
  MODAL_BORDER_RADIUS: 16,
  
  // Safe area (platform specific)
  SAFE_AREA_TOP: Platform.select({
    ios: 44,
    android: 24,
    default: 44,
  }),
  SAFE_AREA_BOTTOM: Platform.select({
    ios: 34,
    android: 0,
    default: 34,
  }),
  
  // Breakpoints
  BREAKPOINT_XS: 320,
  BREAKPOINT_SM: 375,
  BREAKPOINT_MD: 414,
  BREAKPOINT_LG: 768,
  BREAKPOINT_XL: 1024,
  BREAKPOINT_XXL: 1366,
  
  // Device type thresholds
  TABLET_THRESHOLD: 768,
  LARGE_DEVICE_THRESHOLD: 414,
  MEDIUM_DEVICE_THRESHOLD: 375,
  SMALL_DEVICE_THRESHOLD: 320,
  
  // Z-index values
  Z_INDEX_DROPDOWN: 1000,
  Z_INDEX_MODAL: 2000,
  Z_INDEX_TOAST: 3000,
  Z_INDEX_LOADING: 4000,
  
  // Animation easing
  EASING_EASE_IN: 'ease-in',
  EASING_EASE_OUT: 'ease-out',
  EASING_EASE_IN_OUT: 'ease-in-out',
  EASING_LINEAR: 'linear',
  
  // Performance
  FLATLIST_INITIAL_NUM_TO_RENDER: 10,
  FLATLIST_MAX_TO_RENDER_PER_BATCH: 10,
  FLATLIST_WINDOW_SIZE: 10,
  FLATLIST_UPDATE_CELLS_BATCH_PERIOD: 50,
  
  // Image optimization
  IMAGE_QUALITY_HIGH: 0.9,
  IMAGE_QUALITY_MEDIUM: 0.7,
  IMAGE_QUALITY_LOW: 0.5,
  
  // Cache
  CACHE_SIZE_LIMIT: 50 * 1024 * 1024, // 50MB
  CACHE_EXPIRY_TIME: 24 * 60 * 60 * 1000, // 24 hours
  
  // Network
  REQUEST_TIMEOUT: 10000, // 10 seconds
  RETRY_ATTEMPTS: 3,
  RETRY_DELAY: 1000, // 1 second
};

// Export individual constants for easier access
export const {
  HEADER_HEIGHT,
  TAB_BAR_HEIGHT,
  BUTTON_HEIGHT_MD,
  INPUT_HEIGHT_MD,
  CARD_RADIUS_MD,
  ICON_SIZE_MD,
  SPACING_MD,
  FONT_SIZE_MD,
  BORDER_RADIUS_MD,
  SHADOW_RADIUS_MD,
  ELEVATION_MD,
  ANIMATION_DURATION_NORMAL,
  OPACITY_DISABLED,
  BORDER_WIDTH_NORMAL,
  GRID_COLUMNS_2,
  GRID_GAP_MD,
  ASPECT_RATIO_SQUARE,
  TOUCH_TARGET_MIN,
  LOADING_INDICATOR_SIZE_MD,
  PROGRESS_BAR_HEIGHT_MD,
  BADGE_SIZE_MD,
  CHIP_HEIGHT_MD,
  FAB_SIZE_MD,
  TAB_HEIGHT,
  SWITCH_WIDTH,
  CHECKBOX_SIZE_MD,
  RADIO_SIZE_MD,
} = RESPONSIVE_CONSTANTS;
